In [178]:
import pandas as pd
import numpy as np
import datetime
from pandas_datareader import data
import yahoo_finance

In [179]:
start_date = '2014-01-02'
end_date = '2018-12-31'
stocks = data.DataReader(['NDAQ','SNP','^DJI','^N225','^GDAXI','^HSI','^AXJO'], 'yahoo', start_date, end_date)
#print(ndaq.iloc[0,:])
#ndaq['Adj Close'].to_csv('ndaq.csv')
#stock = pd.read_csv('datandaq.csv')
#stock

In [182]:
new_data = pd.DataFrame(stocks['Adj Close'])
new_data.shape

(1425, 7)

In [181]:
usd = data.DataReader('DX-Y.NYB','yahoo',start_date,end_date)
currency = data.DataReader(['DEXJPUS','DEXUSAL','DEXUSEU'],'fred',start_date,end_date) # JPY, AUD,Euro
curr = pd.concat([currency,usd['Adj Close']],axis=1)
updated_curr = curr.dropna(how='all')
updated_curr = updated_curr.rename(columns={'Adj Close':'USD'})
print(updated_curr)

            DEXJPUS  DEXUSAL  DEXUSEU        USD
2014-01-02   104.84   0.8924   1.3670  80.629997
2014-01-03   104.46   0.8976   1.3606  80.790001
2014-01-06   104.38   0.8961   1.3636  80.650002
2014-01-07   104.54   0.8923   1.3618  80.830002
2014-01-08   104.87   0.8909   1.3586  81.040001
2014-01-09   104.74   0.8886   1.3591  81.010002
2014-01-10   104.06   0.8985   1.3664  80.660004
2014-01-13   103.31   0.9053   1.3647  80.510002
2014-01-14   103.80   0.8980   1.3682  80.610001
2014-01-15   104.42   0.8925   1.3604  81.000000
2014-01-16   104.32   0.8802   1.3600  80.900002
2014-01-17   104.32   0.8778   1.3554  81.260002
2014-01-21   104.14   0.8801   1.3560  81.099998
2014-01-22   104.36   0.8839   1.3546  81.169998
2014-01-23   103.65   0.8774   1.3680  80.440002
2014-01-24   102.41   0.8715   1.3680  80.459999
2014-01-27   102.26   0.8735   1.3679  80.500000
2014-01-28   102.80   0.8770   1.3662  80.570000
2014-01-29   102.20   0.8763   1.3663  80.510002
2014-01-30   102.83   0.8771   1.3549  81.089996
2014-01-31   102.28   0.8743   1.3500  81.269997
2014-02-03   101.11   0.8777   1.3523  81.010002
2014-02-04   101.62   0.8935   1.3507  81.120003
2014-02-05   101.38   0.8911   1.3519  81.029999
2014-02-06   101.84   0.8967   1.3604  80.889999
2014-02-07   102.32   0.8959   1.3614  80.690002
2014-02-10   102.14   0.8944   1.3644  80.669998
2014-02-11   102.63   0.9045   1.3654  80.629997
2014-02-12   102.48   0.9028   1.3592  80.680000
2014-02-13   102.20   0.8979   1.3669  80.290001
...             ...      ...      ...        ...
2018-11-15   113.46   0.7269   1.1324  96.930000
2018-11-16   112.76   0.7312   1.1402  96.470001
2018-11-19   112.54   0.7291   1.1448  96.190002
2018-11-20   112.66   0.7246   1.1391  96.809998
2018-11-21   113.06   0.7267   1.1393  96.709999
2018-11-23   112.83   0.7225   1.1332  96.919998
2018-11-26   113.58   0.7230   1.1336  97.070000
2018-11-27   113.84   0.7206   1.1281  97.370003
2018-11-28   113.96   0.7233   1.1286  96.790001
2018-11-29   113.42   0.7314   1.1382  96.779999
2018-11-30   113.54   0.7311   1.1323  97.269997
2018-12-03   113.54   0.7360   1.1356  97.040001
2018-12-04   112.93   0.7353   1.1345  96.970001
2018-12-06   112.46   0.7216   1.1374  96.809998
2018-12-07   112.60   0.7210   1.1390  96.510002
2018-12-10   112.96   0.7190   1.1368  97.220001
2018-12-11   113.41   0.7204   1.1314  97.389999
2018-12-12   113.28   0.7223   1.1362  97.040001
2018-12-13   113.66   0.7228   1.1358  97.059998
2018-12-14   113.35   0.7176   1.1300  97.440002
2018-12-17   112.96   0.7182   1.1339  97.099998
2018-12-18   112.54   0.7172   1.1364  97.139999
2018-12-19   112.15   0.7172   1.1422  97.040001
2018-12-20   111.34   0.7104   1.1432  96.279999
2018-12-21   111.14   0.7072   1.1402  96.959999
2018-12-24      NaN      NaN      NaN  96.550003
2018-12-26   110.45   0.7070   1.1408  97.050003
2018-12-27   110.78   0.7020   1.1412  96.570000
2018-12-28   110.34   0.7044   1.1445  96.389999
2018-12-31   109.70   0.7046   1.1456  96.169998

[1263 rows x 4 columns]

In [183]:
stockCurr = pd.concat([All_stocks,updated_curr],axis=1)
stockCurr.index.names=['Date']
stockCurr

,NDAQ,SNP,^DJI,^GDAXI,^HSI,^N225,^AXJO,DEXJPUS,DEXUSAL,DEXUSEU,USD
Date,,,,,,,,,,,
2014-01-02,35.703281,59.745533,16441.349609,9400.040039,23340.050781,NaN,5350.100098,104.84,0.8924,1.3670,80.629997
2014-01-03,36.231552,58.803719,16469.990234,9435.150391,22817.279297,NaN,NaN,104.46,0.8976,1.3606,80.790001
2014-01-06,36.322628,57.734825,16425.099609,9428.000000,22684.150391,15908.879883,5317.000000,104.38,0.8961,1.3636,80.650002
2014-01-07,36.495670,57.555435,16530.939453,9506.200195,22712.779297,15814.370117,5316.000000,104.54,0.8923,1.3618,80.830002
2014-01-08,36.595867,56.979893,16462.740234,9497.839844,22996.589844,16121.450195,5324.399902,104.87,0.8909,1.3586,81.040001
2014-01-09,36.650517,55.985744,16444.759766,9421.610352,22787.330078,15880.330078,5312.399902,104.74,0.8886,1.3591,81.010002
2014-01-10,36.359051,56.658474,16437.050781,9473.240234,22846.250000,15912.059570,NaN,104.06,0.8985,1.3664,80.660004
2014-01-13,35.657742,56.202511,16257.940430,9510.169922,22888.759766,NaN,5212.000000,103.31,0.9053,1.3647,80.510002
2014-01-14,36.195118,57.465748,16373.860352,9540.509766,22791.279297,15422.400391,5245.399902,103.80,0.8980,1.3682,80.610001
2014-01-15,35.994736,57.271389,16481.939453,9733.809570,22902.000000,15808.730469,5309.100098,104.42,0.8925,1.3604,81.000000
2014-01-16,36.413704,57.009777,16417.009766,9717.709961,22986.410156,15747.200195,5305.899902,104.32,0.8802,1.3600,80.900002
2014-01-17,36.176899,57.727364,16458.560547,9742.959961,23133.349609,15734.459961,NaN,104.32,0.8778,1.3554,81.260002
2014-01-20,NaN,NaN,NaN,9715.900391,22928.949219,15641.679688,5331.500000,NaN,NaN,NaN,NaN
2014-01-21,35.885448,61.143307,16414.439453,9730.120117,23033.119141,15795.959961,5319.799805,104.14,0.8801,1.3560,81.099998
2014-01-22,35.976517,61.943108,16373.339844,9720.110352,23082.250000,15820.959961,5263.000000,104.36,0.8839,1.3546,81.169998
2014-01-23,35.247883,60.029579,16197.349609,9631.040039,22733.900391,15695.889648,5240.899902,103.65,0.8774,1.3680,80.440002
2014-01-24,34.245998,59.401699,15879.110352,9392.019531,22450.060547,15391.559570,NaN,102.41,0.8715,1.3680,80.459999
2014-01-27,33.990982,59.700676,15837.879883,9349.219727,21976.099609,15005.730469,5175.100098,102.26,0.8735,1.3679,80.500000
2014-01-28,34.291546,59.790371,15928.559570,9406.910156,21960.640625,14980.160156,5229.000000,102.80,0.8770,1.3662,80.570000
2014-01-29,33.881683,58.504723,15738.790039,9336.730469,22141.609375,15383.910156,5188.100098,102.20,0.8763,1.3663,80.510002
2014-01-30,34.983746,59.087757,15848.610352,9373.480469,22035.419922,15007.059570,5190.000000,102.83,0.8771,1.3549,81.089996
2014-01-31,34.746941,58.923306,15698.849609,9306.480469,NaN,14914.530273,NaN,102.28,0.8743,1.3500,81.269997
2014-02-03,33.817936,58.123520,15372.799805,9186.519531,NaN,14619.129883,5097.100098,101.11,0.8777,1.3523,81.010002
2014-02-04,34.419060,58.437462,15445.240234,9127.910156,21397.769531,14008.469727,5070.299805,101.62,0.8935,1.3507,81.120003
2014-02-05,34.746941,56.860291,15440.230469,9116.320312,21269.380859,14180.379883,5131.399902,101.38,0.8911,1.3519,81.029999
2014-02-06,34.473690,56.045544,15628.530273,9256.580078,21423.130859,14155.120117,5166.500000,101.84,0.8967,1.3604,80.889999
2014-02-07,34.191368,56.396851,15794.080078,9301.919922,21636.849609,14462.410156,NaN,102.32,0.8959,1.3614,80.690002
2014-02-10,34.164032,55.709175,15801.790039,9289.860352,21579.259766,14718.339844,5254.500000,102.14,0.8944,1.3644,80.669998
2014-02-11,34.947327,57.622719,15994.769531,9478.769531,21962.980469,NaN,5310.100098,102.63,0.9045,1.3654,80.629997
2014-02-12,35.147697,57.846954,15963.940430,9540.000000,22285.789062,14800.059570,5308.100098,102.48,0.9028,1.3592,80.680000
...,...,...,...,...,...,...,...,...,...,...,...
2018-11-20,86.540260,82.360001,24465.640625,11066.410156,25840.339844,21583.119141,5642.799805,112.66,0.7246,1.1391,96.809998
2018-11-21,86.371994,84.029999,24464.689453,11244.169922,25971.470703,21507.539062,5691.299805,113.06,0.7267,1.1393,96.709999
2018-11-22,NaN,NaN,NaN,11138.490234,26019.410156,21646.550781,5716.200195,NaN,NaN,NaN,NaN
2018-11-23,86.965881,81.500000,24285.949219,11192.690430,25927.679688,NaN,NaN,112.83,0.7225,1.1332,96.919998
2018-11-26,88.519913,83.699997,24640.240234,11354.719727,26376.179688,21812.000000,5728.299805,113.58,0.7230,1.1336,97.070000
2018-11-27,88.549606,83.250000,24748.730469,11309.110352,26331.960938,21952.400391,5725.100098,113.84,0.7206,1.1281,97.370003
2018-11-28,89.014824,84.459999,25366.429688,11298.879883,26682.560547,22177.019531,5758.399902,113.96,0.7233,1.1286,96.790001
2018-11-29,89.470139,84.379997,25338.839844,11298.230469,26451.029297,22262.599609,5667.200195,113.42,0.7314,1.1382,96.779999
2018-11-30,90.390678,85.339996,25538.460938,11257.240234,26506.750000,22351.060547,NaN,113.54,0.7311,1.1323,97.269997
2018-12-03,91.707146,88.190002,25826.429688,11465.459961,27182.039062,22574.759766,5713.100098,113.54,0.7360,1.1356,97.040001
2018-12-04,89.480042,86.370003,25027.070312,11335.320312,27260.439453,22036.050781,5668.399902,112.93,0.7353,1.1345,96.970001
2018-12-05,NaN,NaN,NaN,11200.240234,26819.679688,21919.330078,5657.600098,NaN,NaN,NaN,NaN
2018-12-06,88.975227,84.610001,24947.669922,10810.980469,26156.380859,21501.619141,5681.500000,112.46,0.7216,1.1374,96.809998
2018-12-07,86.470978,82.379997,24388.949219,10788.089844,26063.759766,21678.679688,NaN,112.60,0.7210,1.1390,96.510002
2018-12-10,86.213615,81.559998,24423.259766,10622.070312,25752.380859,21219.500000,5575.899902,112.96,0.7190,1.1368,97.220001
2018-12-11,86.421478,81.489998,24370.240234,10780.509766,25771.669922,21148.019531,5653.500000,113.41,0.7204,1.1314,97.389999
2018-12-12,86.599648,82.489998,24527.269531,10929.429688,26186.710938,21602.750000,5661.600098,113.28,0.7223,1.1362,97.040001
2018-12-13,86.569801,84.000000,24597.380859,10924.700195,26524.349609,21816.189453,5602.000000,113.66,0.7228,1.1358,97.059998
2018-12-14,86.092293,82.400002,24100.509766,10865.769531,26094.789062,21374.830078,NaN,113.35,0.7176,1.1300,97.440002
2018-12-17,84.808968,80.940002,23592.980469,10772.200195,26087.980469,21506.880859,5589.500000,112.96,0.7182,1.1339,97.099998
2018-12-18,83.306770,79.360001,23675.640625,10740.889648,25814.250000,21115.449219,5580.600098,112.54,0.7172,1.1364,97.139999
2018-12-19,82.580551,77.180000,23323.660156,10766.209961,25865.390625,20987.919922,5505.799805,112.15,0.7172,1.1422,97.040001
2018-12-20,80.590904,76.750000,22859.599609,10611.099609,25623.529297,20392.580078,5467.600098,111.34,0.7104,1.1432,96.279999
2018-12-21,79.098663,75.660004,22445.369141,10633.820312,25753.419922,20166.189453,NaN,111.14,0.7072,1.1402,96.959999
2018-12-24,76.352936,74.309998,21792.199219,NaN,25651.380859,NaN,NaN,NaN,NaN,NaN,96.550003
2018-12-25,NaN,NaN,NaN,NaN,NaN,19155.740234,NaN,NaN,NaN,NaN,NaN
2018-12-26,78.859901,77.339996,22878.449219,NaN,NaN,19327.060547,5597.200195,110.45,0.7070,1.1408,97.050003
2018-12-27,80.272560,72.970001,23138.820312,10381.509766,25478.880859,20077.619141,5654.299805,110.78,0.7020,1.1412,96.570000
2018-12-28,80.113380,69.750000,23062.400391,10558.959961,25504.199219,20014.769531,NaN,110.34,0.7044,1.1445,96.389999
2018-12-31,81.148003,70.599998,23327.460938,NaN,25845.699219,NaN,NaN,109.70,0.7046,1.1456,96.169998

In [67]:
'''gold= pd.read_csv('Data\Gold.csv')
gold = gold.iloc[::-1]
gold = gold.set_index('Date')
gold = gold.rename(columns={'Price':'Gold'})'''

['Date', 'Price', 'Open', 'High', 'Low', 'Vol.', 'Change %']

In [187]:
#gold = data.DataReader('GOLDAMGBD228NLBM','fred',start_date,end_date)
gold = pd.read_csv('Data\GOLDAMGBD228NLBM.csv')
gold = gold.set_index('Date')

In [185]:
platinium = pd.read_csv('Data\Platinum.csv')
platinium = platinium.set_index('Date')

In [188]:
oil = pd.read_csv('Data\oil.csv')
oil = oil.set_index('Date')
pla_oil = platinium.merge(oil,on='Date')
pla_oil

             Platinium      Oil
Date
02-01-2014     1404.60   95.440
03-01-2014     1414.20   93.960
06-01-2014     1416.40   93.430
07-01-2014     1415.40   93.670
08-01-2014     1414.20   92.330
09-01-2014     1419.90   91.660
10-01-2014     1436.90   92.720
13-01-2014     1443.90   91.800
14-01-2014     1433.80   92.590
15-01-2014     1428.60   94.206
16-01-2014     1431.50   94.016
17-01-2014     1454.10   94.502
21-01-2014     1453.50   94.974
22-01-2014     1462.40   96.730
23-01-2014     1463.20   97.320
24-01-2014     1428.60   96.640
27-01-2014     1421.10   95.720
28-01-2014     1409.40   97.410
29-01-2014     1408.10   97.360
30-01-2014     1382.30   98.230
31-01-2014     1375.70   97.490
03-02-2014     1386.60   96.430
04-02-2014     1373.40   97.190
05-02-2014     1379.30   97.380
06-02-2014     1374.90   97.840
07-02-2014     1379.20   99.880
10-02-2014     1385.90  100.060
11-02-2014     1387.80   99.940
12-02-2014     1407.30  100.370
13-02-2014     1416.60  100.350
...                ...      ...
16-11-2018      846.60   56.592
19-11-2018      857.60   57.112
20-11-2018      847.00   53.430
21-11-2018      850.60   54.630
23-11-2018      845.00   50.420
26-11-2018      847.80   51.630
27-11-2018      835.30   51.560
28-11-2018      826.30   50.290
29-11-2018      820.90   51.450
30-11-2018      799.80   50.930
03-12-2018      810.70   52.950
04-12-2018      804.20   53.250
05-12-2018      802.00   52.890
06-12-2018      789.60   51.490
07-12-2018      790.40   52.610
10-12-2018      782.10   51.000
11-12-2018      785.50   51.650
12-12-2018      807.10   51.150
13-12-2018      797.50   52.580
14-12-2018      785.30   51.254
17-12-2018      795.90   50.008
18-12-2018      794.80   46.456
19-12-2018      796.00   47.976
20-12-2018      795.80   45.880
21-12-2018      795.80   45.590
24-12-2018      789.40   42.530
26-12-2018      801.06   46.220
27-12-2018      798.22   44.610
28-12-2018      793.68   45.330
31-12-2018      799.66   45.410

[1258 rows x 2 columns]

In [191]:
commodities = pd.merge(pla_oil,gold,on='Date')
commodities

             Platinium      Oil GOLDAMGBD228NLBM
Date
02-01-2014     1404.60   95.440          1219.75
03-01-2014     1414.20   93.960          1232.25
06-01-2014     1416.40   93.430             1238
07-01-2014     1415.40   93.670           1237.5
08-01-2014     1414.20   92.330           1226.5
09-01-2014     1419.90   91.660             1226
10-01-2014     1436.90   92.720          1232.25
13-01-2014     1443.90   91.800             1246
14-01-2014     1433.80   92.590          1248.75
15-01-2014     1428.60   94.206             1238
16-01-2014     1431.50   94.016          1237.25
17-01-2014     1454.10   94.502             1241
21-01-2014     1453.50   94.974          1247.75
22-01-2014     1462.40   96.730           1239.5
23-01-2014     1463.20   97.320          1244.25
24-01-2014     1428.60   96.640          1259.25
27-01-2014     1421.10   95.720             1270
28-01-2014     1409.40   97.410           1253.5
29-01-2014     1408.10   97.360          1254.75
30-01-2014     1382.30   98.230             1254
31-01-2014     1375.70   97.490           1246.5
03-02-2014     1386.60   96.430           1246.5
04-02-2014     1373.40   97.190             1253
05-02-2014     1379.30   97.380             1257
06-02-2014     1374.90   97.840           1258.5
07-02-2014     1379.20   99.880             1260
10-02-2014     1385.90  100.060           1273.5
11-02-2014     1387.80   99.940          1282.75
12-02-2014     1407.30  100.370           1286.5
13-02-2014     1416.60  100.350          1290.25
...                ...      ...              ...
16-11-2018      846.60   56.592           1215.8
19-11-2018      857.60   57.112          1223.55
20-11-2018      847.00   53.430           1223.1
21-11-2018      850.60   54.630             1224
23-11-2018      845.00   50.420          1222.15
26-11-2018      847.80   51.630          1226.65
27-11-2018      835.30   51.560          1225.05
28-11-2018      826.30   50.290           1213.2
29-11-2018      820.90   51.450          1226.45
30-11-2018      799.80   50.930          1220.45
03-12-2018      810.70   52.950          1231.05
04-12-2018      804.20   53.250          1239.25
05-12-2018      802.00   52.890          1236.15
06-12-2018      789.60   51.490          1236.45
07-12-2018      790.40   52.610           1241.2
10-12-2018      782.10   51.000           1246.8
11-12-2018      785.50   51.650          1248.25
12-12-2018      807.10   51.150          1244.75
13-12-2018      797.50   52.580          1244.45
14-12-2018      785.30   51.254          1239.15
17-12-2018      795.90   50.008           1239.1
18-12-2018      794.80   46.456           1248.8
19-12-2018      796.00   47.976           1248.6
20-12-2018      795.80   45.880             1255
21-12-2018      795.80   45.590           1257.6
24-12-2018      789.40   42.530          1261.25
26-12-2018      801.06   46.220                .
27-12-2018      798.22   44.610           1271.1
28-12-2018      793.68   45.330          1277.25
31-12-2018      799.66   45.410          1281.65

[1258 rows x 3 columns]

In [192]:
print(stockCurr.index.dtype)
commodities.index = pd.to_datetime(commodities.index)
print(commodities.index.dtype)
stockCurrCom = pd.merge(stockCurr,commodities,on='Date',how='left')

datetime64[ns]
datetime64[ns]

In [193]:
stockCurrCom
stockCurrCom.to_csv('Stock_Currency_Commodity.csv')

,NDAQ,SNP,^DJI,^GDAXI,^HSI,^N225,^AXJO,DEXJPUS,DEXUSAL,DEXUSEU,USD,Platinium,Oil,GOLDAMGBD228NLBM
Date,,,,,,,,,,,,,,
2014-01-02,35.703281,59.745533,16441.349609,9400.040039,23340.050781,NaN,5350.100098,104.84,0.8924,1.3670,80.629997,NaN,NaN,NaN
2014-01-03,36.231552,58.803719,16469.990234,9435.150391,22817.279297,NaN,NaN,104.46,0.8976,1.3606,80.790001,NaN,NaN,NaN
2014-01-06,36.322628,57.734825,16425.099609,9428.000000,22684.150391,15908.879883,5317.000000,104.38,0.8961,1.3636,80.650002,NaN,NaN,NaN
2014-01-07,36.495670,57.555435,16530.939453,9506.200195,22712.779297,15814.370117,5316.000000,104.54,0.8923,1.3618,80.830002,1515.00,105.340,1325.75
2014-01-08,36.595867,56.979893,16462.740234,9497.839844,22996.589844,16121.450195,5324.399902,104.87,0.8909,1.3586,81.040001,1463.30,97.880,1284.5
2014-01-09,36.650517,55.985744,16444.759766,9421.610352,22787.330078,15880.330078,5312.399902,104.74,0.8886,1.3591,81.010002,NaN,NaN,NaN
2014-01-10,36.359051,56.658474,16437.050781,9473.240234,22846.250000,15912.059570,NaN,104.06,0.8985,1.3664,80.660004,1289.60,90.730,1208.5
2014-01-13,35.657742,56.202511,16257.940430,9510.169922,22888.759766,NaN,5212.000000,103.31,0.9053,1.3647,80.510002,1443.90,91.800,1246
2014-01-14,36.195118,57.465748,16373.860352,9540.509766,22791.279297,15422.400391,5245.399902,103.80,0.8980,1.3682,80.610001,1433.80,92.590,1248.75
2014-01-15,35.994736,57.271389,16481.939453,9733.809570,22902.000000,15808.730469,5309.100098,104.42,0.8925,1.3604,81.000000,1428.60,94.206,1238
2014-01-16,36.413704,57.009777,16417.009766,9717.709961,22986.410156,15747.200195,5305.899902,104.32,0.8802,1.3600,80.900002,1431.50,94.016,1237.25
2014-01-17,36.176899,57.727364,16458.560547,9742.959961,23133.349609,15734.459961,NaN,104.32,0.8778,1.3554,81.260002,1454.10,94.502,1241
2014-01-20,NaN,NaN,NaN,9715.900391,22928.949219,15641.679688,5331.500000,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2014-01-21,35.885448,61.143307,16414.439453,9730.120117,23033.119141,15795.959961,5319.799805,104.14,0.8801,1.3560,81.099998,1453.50,94.974,1247.75
2014-01-22,35.976517,61.943108,16373.339844,9720.110352,23082.250000,15820.959961,5263.000000,104.36,0.8839,1.3546,81.169998,1462.40,96.730,1239.5
2014-01-23,35.247883,60.029579,16197.349609,9631.040039,22733.900391,15695.889648,5240.899902,103.65,0.8774,1.3680,80.440002,1463.20,97.320,1244.25
2014-01-24,34.245998,59.401699,15879.110352,9392.019531,22450.060547,15391.559570,NaN,102.41,0.8715,1.3680,80.459999,1428.60,96.640,1259.25
2014-01-27,33.990982,59.700676,15837.879883,9349.219727,21976.099609,15005.730469,5175.100098,102.26,0.8735,1.3679,80.500000,1421.10,95.720,1270
2014-01-28,34.291546,59.790371,15928.559570,9406.910156,21960.640625,14980.160156,5229.000000,102.80,0.8770,1.3662,80.570000,1409.40,97.410,1253.5
2014-01-29,33.881683,58.504723,15738.790039,9336.730469,22141.609375,15383.910156,5188.100098,102.20,0.8763,1.3663,80.510002,1408.10,97.360,1254.75
2014-01-30,34.983746,59.087757,15848.610352,9373.480469,22035.419922,15007.059570,5190.000000,102.83,0.8771,1.3549,81.089996,1382.30,98.230,1254
2014-01-31,34.746941,58.923306,15698.849609,9306.480469,NaN,14914.530273,NaN,102.28,0.8743,1.3500,81.269997,1375.70,97.490,1246.5
2014-02-03,33.817936,58.123520,15372.799805,9186.519531,NaN,14619.129883,5097.100098,101.11,0.8777,1.3523,81.010002,NaN,NaN,NaN
2014-02-04,34.419060,58.437462,15445.240234,9127.910156,21397.769531,14008.469727,5070.299805,101.62,0.8935,1.3507,81.120003,1438.70,99.620,1284
2014-02-05,34.746941,56.860291,15440.230469,9116.320312,21269.380859,14180.379883,5131.399902,101.38,0.8911,1.3519,81.029999,1440.70,99.760,1285
2014-02-06,34.473690,56.045544,15628.530273,9256.580078,21423.130859,14155.120117,5166.500000,101.84,0.8967,1.3604,80.889999,1436.70,102.470,1244.75
2014-02-07,34.191368,56.396851,15794.080078,9301.919922,21636.849609,14462.410156,NaN,102.32,0.8959,1.3614,80.690002,1511.50,104.480,1326.75
2014-02-10,34.164032,55.709175,15801.790039,9289.860352,21579.259766,14718.339844,5254.500000,102.14,0.8944,1.3644,80.669998,1270.40,91.010,1214.5
2014-02-11,34.947327,57.622719,15994.769531,9478.769531,21962.980469,NaN,5310.100098,102.63,0.9045,1.3654,80.629997,NaN,NaN,NaN
2014-02-12,35.147697,57.846954,15963.940430,9540.000000,22285.789062,14800.059570,5308.100098,102.48,0.9028,1.3592,80.680000,1217.50,66.880,1197
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2018-11-20,86.540260,82.360001,24465.640625,11066.410156,25840.339844,21583.119141,5642.799805,112.66,0.7246,1.1391,96.809998,847.00,53.430,1223.1
2018-11-21,86.371994,84.029999,24464.689453,11244.169922,25971.470703,21507.539062,5691.299805,113.06,0.7267,1.1393,96.709999,850.60,54.630,1224
2018-11-22,NaN,NaN,NaN,11138.490234,26019.410156,21646.550781,5716.200195,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2018-11-23,86.965881,81.500000,24285.949219,11192.690430,25927.679688,NaN,NaN,112.83,0.7225,1.1332,96.919998,845.00,50.420,1222.15
2018-11-26,88.519913,83.699997,24640.240234,11354.719727,26376.179688,21812.000000,5728.299805,113.58,0.7230,1.1336,97.070000,847.80,51.630,1226.65
2018-11-27,88.549606,83.250000,24748.730469,11309.110352,26331.960938,21952.400391,5725.100098,113.84,0.7206,1.1281,97.370003,835.30,51.560,1225.05
2018-11-28,89.014824,84.459999,25366.429688,11298.879883,26682.560547,22177.019531,5758.399902,113.96,0.7233,1.1286,96.790001,826.30,50.290,1213.2
2018-11-29,89.470139,84.379997,25338.839844,11298.230469,26451.029297,22262.599609,5667.200195,113.42,0.7314,1.1382,96.779999,820.90,51.450,1226.45
2018-11-30,90.390678,85.339996,25538.460938,11257.240234,26506.750000,22351.060547,NaN,113.54,0.7311,1.1323,97.269997,799.80,50.930,1220.45
2018-12-03,91.707146,88.190002,25826.429688,11465.459961,27182.039062,22574.759766,5713.100098,113.54,0.7360,1.1356,97.040001,962.90,61.360,1317.25
2018-12-04,89.480042,86.370003,25027.070312,11335.320312,27260.439453,22036.050781,5668.399902,112.93,0.7353,1.1345,96.970001,934.80,67.070,1345.9
2018-12-05,NaN,NaN,NaN,11200.240234,26819.679688,21919.330078,5657.600098,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2018-12-06,88.975227,84.610001,24947.669922,10810.980469,26156.380859,21501.619141,5681.500000,112.46,0.7216,1.1374,96.809998,901.50,66.360,1298.3
2018-12-07,86.470978,82.379997,24388.949219,10788.089844,26063.759766,21678.679688,NaN,112.60,0.7210,1.1390,96.510002,846.40,70.330,1244.85
2018-12-10,86.213615,81.559998,24423.259766,10622.070312,25752.380859,21219.500000,5575.899902,112.96,0.7190,1.1368,97.220001,840.00,71.340,1218.75
2018-12-11,86.421478,81.489998,24370.240234,10780.509766,25771.669922,21148.019531,5653.500000,113.41,0.7204,1.1314,97.389999,845.30,59.930,1207.05
2018-12-12,86.599648,82.489998,24527.269531,10929.429688,26186.710938,21602.750000,5661.600098,113.28,0.7223,1.1362,97.040001,807.10,51.150,1244.75
2018-12-13,86.569801,84.000000,24597.380859,10924.700195,26524.349609,21816.189453,5602.000000,113.66,0.7228,1.1358,97.059998,797.50,52.580,1244.45
2018-12-14,86.092293,82.400002,24100.509766,10865.769531,26094.789062,21374.830078,NaN,113.35,0.7176,1.1300,97.440002,785.30,51.254,1239.15
2018-12-17,84.808968,80.940002,23592.980469,10772.200195,26087.980469,21506.880859,5589.500000,112.96,0.7182,1.1339,97.099998,795.90,50.008,1239.1
2018-12-18,83.306770,79.360001,23675.640625,10740.889648,25814.250000,21115.449219,5580.600098,112.54,0.7172,1.1364,97.139999,794.80,46.456,1248.8
2018-12-19,82.580551,77.180000,23323.660156,10766.209961,25865.390625,20987.919922,5505.799805,112.15,0.7172,1.1422,97.040001,796.00,47.976,1248.6
2018-12-20,80.590904,76.750000,22859.599609,10611.099609,25623.529297,20392.580078,5467.600098,111.34,0.7104,1.1432,96.279999,795.80,45.880,1255
2018-12-21,79.098663,75.660004,22445.369141,10633.820312,25753.419922,20166.189453,NaN,111.14,0.7072,1.1402,96.959999,795.80,45.590,1257.6
2018-12-24,76.352936,74.309998,21792.199219,NaN,25651.380859,NaN,NaN,NaN,NaN,NaN,96.550003,789.40,42.530,1261.25
2018-12-25,NaN,NaN,NaN,NaN,NaN,19155.740234,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2018-12-26,78.859901,77.339996,22878.449219,NaN,NaN,19327.060547,5597.200195,110.45,0.7070,1.1408,97.050003,801.06,46.220,.
2018-12-27,80.272560,72.970001,23138.820312,10381.509766,25478.880859,20077.619141,5654.299805,110.78,0.7020,1.1412,96.570000,798.22,44.610,1271.1
2018-12-28,80.113380,69.750000,23062.400391,10558.959961,25504.199219,20014.769531,NaN,110.34,0.7044,1.1445,96.389999,793.68,45.330,1277.25
2018-12-31,81.148003,70.599998,23327.460938,NaN,25845.699219,NaN,NaN,109.70,0.7046,1.1456,96.169998,799.66,45.410,1281.65